ServiceHost = "localhost"
ServicePort = 9005

host = "localhost"
port = 5432
user = "alex"
password = "password123"
dbname = "RIP"
sslmode = "disable"

redis_host = "localhost"
redis_port = 6379
redis_db = 0